title: Ciencia de Datos y Machine Learning. Aplicaciones en R
subtitle: Maestría en Generación y Análisis de Información Estadística - UNTREF
description: Materiales del curso       
show_downloads: true
theme: jekyll-theme-cayman
